### ISSUE TITLE
MLSD support, start() behavior

### ISSUE THREAD

**Issue by alextekartik** [abdelaziz-mahdy/ftp_server#11]
Hi and thank you for woring on a FTP server. I'm trying to do unit test using ftpconnect (one client dart package, but maybe some others exists) and I'm facing several issues:
- MLSD support (for listing files) is missing (ftpconnect seems to be using this)
- start() does not return when the server is ready (i.e. how to I know when the server is ready

This prevents (me!) from doing basic unit test such as connecting and downloading files all in dart!

basically I'd like to be able to perform some tests using the following structure:

```dart
@TestOn('vm')
library;

import 'dart:io';

import 'package:ftp_server/ftp_server.dart';
import 'package:ftp_server/server_type.dart';
import 'package:path/path.dart';
import 'package:test/test.dart';

var port = 7079;
var testDir = join('.local', 'ftp', 'test');
Future<void> main() async {
  group('fs_ftp', () {
    late FtpServer server;
    setUpAll(() async {
      server = FtpServer(
        port,
        username: 'admin',
        password: 'admin',
        sharedDirectories: [testDir],
        startingDirectory: testDir,
        serverType: ServerType.readAndWrite,
      );
     
      // Unfortunately this hangs, I'd like it to return when the server is ready
      await server.start();
    });
    tearDown(() async {
      await server.stop();
    });
    test('some test', () async {
      // ...
    });
  });
}

**Comment by abdelaziz-mahdy** [comment]
Hi check the ftps branch I added some of the missing commands there and improved working of the ftps support 


I think splitting it to and providing the missing commands as an update is the faster approach since ftps is not working correctly even though I am following the specs

**Comment by abdelaziz-mahdy** [comment]
Also start in background will not hang, and I will add a ready completer so you know when server is ready

**Comment by abdelaziz-mahdy** [comment]
i made a pr adding the missing commands, and the start the `startInBackground` will be your best choice in the case of the tests, i use it too

**Comment by alextekartik** [comment]
That was fast! Perfect, thank you

**Comment by abdelaziz-mahdy** [comment]
> That was fast! Perfect, thank you

Glad to help, let me know if there are cases I didn't cover in my tests too, I would appreciate it

**Comment by alextekartik** [comment]
Will do! so far so good. I'm only mainly testing listing directory and downloading/uploading files
